version: '3'
services:
  app:
    image: ghcr.io/thesafatem/chgk-polling-bot/chgk-polling-bot:develop
    build: .
    container_name: app
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 8080:8080
    restart: always
    command: npm run start
    env_file:
      - .env