version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    # network_mode: host
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chgkPollingBot  
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

#   app:
#     # image: ghcr.io/thesafatem/chgk-polling-bot/chgk-polling-bot:develop
#     image: chgk-polling-bot:latest
#     build: .
#     container_name: app
#     network_mode: host
#     volumes:
#       - .:/opt/app
#       - /opt/app/node_modules
#     ports:
#       - 8080:8080
#     restart: always
#     command: npm run start
#     env_file:
#       - .env
#     depends_on:
#       - mongo
    
volumes:
  mongo-data: